### ISSUE TITLE
fideslang: incompatibility with python < `3.10` caused by pydantic bug

### ISSUE THREAD

**Issue by adamsachs** [IABTechLab/fideslang#108]
### Bug Description

Corresponding ticket to https://github.com/ethyca/fides/issues/3358 which fixes the problem in `fides`. But we should fix it also here in `fideslang` to keep it compatible in its own right with python < `3.10`.

#### Steps to Reproduce

- try "using" `fideslang` in a python env < `3.10`

### Expected behavior

- projects/apps that run on python < `3.10` should be able to easily leverage `fideslang`

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

See https://github.com/ethyca/fides/issues/3358 for more context

**Comment by Roger-Ethyca** [comment]
moving to done
