### ISSUE TITLE
tech debt - consider reverting `Literal` workaround for pydantic bug

### ISSUE THREAD

**Issue by adamsachs** [IABTechLab/fideslang#110]
### Is your feature request related to a specific problem?

https://github.com/ethyca/fideslang/pull/109 had a workaround for a pydantic bug. we should consider reverting this workaround in due course, if possible, just to clear out tech debt.

### Describe the solution you'd like

will the underlying bug(s) have been addressed at a certain point so that we can revert the change?

### Describe alternatives you've considered, if any

keep the workaround in place

### Additional context

keeping track of tech debt 😄

**Comment by adamsachs** [comment]
pydantic addressed the issue in https://github.com/pydantic/pydantic/releases/tag/v1.10.8, we could look to bump our dependency to take advantage of the fix

**Comment by Roger-Ethyca** [comment]
moving to done
