### ISSUE TITLE
Taxonomy visualizer image not showing 

### ISSUE THREAD

**Issue by markethyca** [IABTechLab/fideslang#118]
### Docs Update Description

The taxonomy visualization image is not working and hasn't been for a few days.  It's very helpful to see.  https://ethyca.github.io/fideslang/

 _Describe what you'd like to see documented, and link the page if applicable_

### Additional context

_Add any other context about the problem here._

**Comment by ThomasLaPiana** [comment]
Looks like this is fixed now

**Comment by ThomasLaPiana** [comment]
fixed in #123
