### ISSUE TITLE
Unpin to pydantic < 1.10.0

### ISSUE THREAD

**Issue by ewdurbin** [IABTechLab/fideslang#119]
### Is your feature request related to a specific problem?

Trying to use fideslang as a dependency with a project that uses pydantic > 1.10.0 leads to conflicts.

pydantic 1.10 series has been released for nearly 10 months, many projects have updated to support it.

When trying to use fideslang as a library in pypi/warehouse to add fides dataset checks as part of our CI, I found that this ceiling blocks us from doing so.

### Describe the solution you'd like

Update fideslang to support `pydantic>=1.8.1,<1.11.0`.

### Describe alternatives you've considered, if any

N/A

### Additional context

N/A

**Comment by ewdurbin** [comment]
#124 unblocks this. #122 implements it as part of larger work.

curious if the `<1.11.0` part of #122 should be spun out so a release candidate could be tagged. (this is selfish as not having a release on PyPI is blocking me from moving forward with my work on adding dataset management to CI... for PyPI)

**Comment by ThomasLaPiana** [comment]
@ewdurbin it looks like #124 is good to go? If so I can fast track a review for it and we can cut a new `fideslang` release to unblock you in a day or two? Does that work for you?

**Comment by ewdurbin** [comment]
I think #124 is workable! Your call!

**Comment by ThomasLaPiana** [comment]
> I think #124 is workable! Your call!

I agree 🙂 I'll take a look!
