### ISSUE TITLE
The `meta` field validation is too loose

### ISSUE THREAD

**Issue by ThomasLaPiana** [IABTechLab/fideslang#127]
### Bug Description

The `meta` field now allows `bytes`, which immediately blow up when serialized to JSON

### Expected behavior

The `meta` field should automatically convert all bytes to strings so that it can be JSON serialized and sent via API

### Additional context

This bug was found in `fidesplus` when the system scanner tests blew up

**Comment by rsilvery** [comment]
@Roger-Ethyca  can we confirm that this is still an issue?
