### ISSUE TITLE
issues with mypy typing when importing `fideslang`

### ISSUE THREAD

**Issue by adamsachs** [IABTechLab/fideslang#138]
### Bug Description

Still not 100% sure this is a bug in `fideslang`, but something seems to have changed with the packaging updates in `1.4.3` that's making our mypy runs in `fides` complain about our imports of `fideslang`, if using `fideslang>=1.4.3`.

We need to get this fixed one way or another (again, the "fix" may turn out to be adjusting something over in the dependent library, e.g. `fides`!) since it's causing false negatives and CI failures in `fides` and `fidesplus`.

#### Steps to Reproduce

1. run `nox -s mypy` in `fides` (or `fidesplus`)
- also can be noticed in CI failures on `main` of `fides`, e.g. https://github.com/ethyca/fides/actions/runs/5588801027/jobs/10216115614

### Expected behavior

we should be effectively not receiving these errors in our dependent libraries, or we should be effectively suppressing them!

### Additional context

This was noticed and [discussed first on this draft PR](https://github.com/ethyca/fides/pull/3784#issuecomment-1636424081). i figured i'd make a proper ticket out of it now, since it's now causing CI failures on `main` in both repos.

We can re-ticket over in `fides` and `fidesplus` if this is a problem on their side in how they're referencing `fideslang` now with the new packaging scheme.

**Comment by ThomasLaPiana** [comment]
@adamsachs I think I've got the issues figured out!

Even though we had added `py.typed` to the `MANIFEST.in`, I never actually set `include_package_data` to `True` in `setup.py` so it was never included...lol woops

So these are all valid errors in `fides`, and they're cropping up now because building with `pyproject.toml` the `include_package_data` value _defaults_ to `true`!

I'll start going through and fixing all of these errors in `fides`

**Comment by adamsachs** [comment]
> @adamsachs I think I've got the issues figured out!
> 
> Even though we had added `py.typed` to the `MANIFEST.in`, I never actually set `include_package_data` to `True` in `setup.py` so it was never included...lol woops
> 
> So these are all valid errors in `fides`, and they're cropping up now because building with `pyproject.toml` the `include_package_data` value _defaults_ to `true`!
> 
> I'll start going through and fixing all of these errors in `fides`

ah ha! makes a lot of sense. thanks a bunch for tracking down 👍  - let me know if i can help with cleaning some of the stuff up on the `fides` and `fidesplus` side

**Comment by ThomasLaPiana** [comment]
@adamsachs thank you for the offer! I'm slowly chewing through the `fides` ones but I _really_ need to get started on the DSR 2.0 work, so it's my secondary priority

**Comment by adamsachs** [comment]
> @adamsachs thank you for the offer! I'm slowly chewing through the `fides` ones but I _really_ need to get started on the DSR 2.0 work, so it's my secondary priority

OK sounds good 👍 . i've also got some higher priority things i think i need to make progress on, so i can't look at the moment (a bit of an empty offer i made, sorry! 😬 ). but if i find some time i could try to start knocking off the `fidesplus` ones.

if you do make any progress that's worth checkpointing, maybe throw your incremental progress on a branch in case it'd make sense for me or someone else to pick up from where you are?

**Comment by ThomasLaPiana** [comment]
@adamsachs you know me, PR first thing! https://github.com/ethyca/fides/pull/3839
