### ISSUE TITLE
Deprecate legal_basis , legitimate_interest, and legitimate_interest_impact_assessment in taxonomy

### ISSUE THREAD

**Issue by rsilvery** [IABTechLab/fideslang#139]
When #3827 is complete, we need to deprecate these fields in fideslang and provide a migration path.

**Comment by pattisdr** [comment]
Reopening, I am not sure if I am deprecating these yet in the same body of work

**Comment by rsilvery** [comment]
We are, paired with #3907 that we'll deliver in this release.

**Comment by pattisdr** [comment]
Fideslang support here: https://github.com/ethyca/fideslang/pull/146, deprecates these fields, and others in System, PrivacyDeclaration, Data Use, and Dataset.

**Comment by Roger-Ethyca** [comment]
moving to done
