### ISSUE TITLE
Deprecate Registries 

### ISSUE THREAD

**Issue by pattisdr** [IABTechLab/fideslang#170]
### Is your feature request related to a specific problem?

We have registry fields on systems and registry tables that are not being used and causing confusion.  Let's remove them if we can!

https://github.com/ethyca/fides/pull/4116#discussion_r1333807954

> registries are an extremely old and never-used feature ...

> It was conceived as a way to help organizations organize their fides resources into sub-units. Specifically you could assign systems to a registry to logically "group" them. This use-case has never materialized

### Describe the solution you'd like

_A description of what you want to happen._

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by NevilleS** [comment]
Cloned to https://github.com/ethyca/fideslang/issues/1
