### ISSUE TITLE
Add some missing TCF-related fields to `System` model

### ISSUE THREAD

**Issue by adamsachs** [IABTechLab/fideslang#172]
### Is your feature request related to a specific problem?

We need to add these fields to the `System` model:

- `cookie_max_age_seconds`: `Optional[int]`
- `uses_cookies`: `bool`, `default=False`
- `cookie_refresh`: `bool`, `default=False`
- `uses_non_cookie_access`: `bool`, `default=False`
- `legitimate_interest_disclosure_url`: `Optional[AnyUrl]`

### Describe the solution you'd like

Update the `System` model, shouldn't be more complexity than that

### Describe alternatives you've considered, if any

n/a

### Additional context

broader ticket covering the updates across our stack: https://ethyca.atlassian.net/browse/PROD-1147

**Comment by Roger-Ethyca** [comment]
moving to done
