### ISSUE TITLE
add `flexible_legal_basis_for_processing` field

### ISSUE THREAD

**Issue by adamsachs** [IABTechLab/fideslang#176]
### Is your feature request related to a specific problem?

There's been discussion about anticipating the need to mark a given `PrivacyDeclaration` as having a _flexible_ legal basis, i.e. one that can be edited per-instance and is not purely determined by upstream sources.

**NOTE**: we'll also need a corresponding update (issue) in `fides` to update the DB model (and perform a migration) to get this change fully integrated!

### Describe the solution you'd like

add a new field, `flexible_legal_basis_for_processing`, to the `PrivacyDeclaration` model. default should be `False`.

### Describe alternatives you've considered, if any

hold off on making this change in fideslang (and fides) until we've solidified the requirement, if more solidification is needed!

### Additional context

see some internal comms for context: 
- https://ethyca.atlassian.net/wiki/spaces/EN/pages/2806415398?focusedCommentId=2806579295
- https://ethyca.slack.com/archives/C05E74TR0BB/p1696873548747899?thread_ts=1696870072.062149&cid=C05E74TR0BB

**Comment by Roger-Ethyca** [comment]
moving to done
