### ISSUE TITLE
Enforce at least one "tag" set on each system

### ISSUE THREAD

**Issue by ThomasLaPiana** [IABTechLab/fideslang#44]
### Is your feature request related to a specific problem?

Once #43 is implemented, we would like to enforce that each system has at least one "tag"

### Describe the solution you'd like

Add a pydantic validator to make sure that the "tag" isn't left empty for any systems

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by ThomasLaPiana** [comment]
@NevilleS we are able to surgically enforce tag existence requirements on systems only, if that's what we're looking for

**Comment by NevilleS** [comment]
Personally, I'd like to make this something we elect to enforce only in the UI layer. If we were to make it a language requirement, I'd at least want a config variable to turn it on and off. For example, if we turned this on now, we'd break all existing fidesctl deployments 😄

**Comment by ThomasLaPiana** [comment]
very correct! Would you like to close this for now? @NevilleS

**Comment by NevilleS** [comment]
Yes, happy to close this one. If we do this, we'll focus on a layer above fideslang
