### ISSUE TITLE
Remove the identifiable/nonidentifiable subcategories in data_categoires

### ISSUE THREAD

**Issue by mfbrown** [IABTechLab/fideslang#59]
### Describe the solution you'd like

The identifiable / nonidentifiable categories tend to confuse users; especially engineers who are attempting to classify a given field. We received this feedback from Momentive, Twitter, Ikea, and Walmart

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by SteveDMurphy** [comment]
Combined with #58
