### ISSUE TITLE
Move account to a subcategory of user, or remove it as a category

### ISSUE THREAD

**Issue by mfbrown** [IABTechLab/fideslang#60]
### Describe the solution you'd like
Although users have generally not complained about this, I think most don’t realize that the account category exists and why it should be used. The intent of account is to handle the common case where data used to manage a user’s account (e.g. an email address used to sign-in) may need to be processed differently than data used for non-account purposes (e.g. an email address used to contact them for support).

However, this distinction seems to not be intuitive to early users, and in fact the lack of questions about it seems to imply that it’s just not noticed! Therefore, it might be more intuitive and useful if we had two sibling subcategories, e.g. ...account.email and ...contact.email for this purpose.

Alternatively, it may be easier to remove it entirely. The distinction between account and contact, for example, might be better modeled by applying two different data_use annotations (e.g. provide vs. improve).

Now, we have data categories like:

- user.provided.identifiable.contact.email
- user.provided.identifiable.contact.phone_number
- account.contact.email
- account.contact.phone_number

After, the account category would be moved to a subcategory of user:

- user.provided.identifiable.contact.email
- user.provided.identifiable.contact.phone_number
- user.provided.identifiable.account.email
- user.provided.identifiable.account.phone_number

Alternatively, the account category could be deleted entirely and migrated to use user.provided.identifiable.contact equivalents instead.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by SteveDMurphy** [comment]
Combined with #58
