### ISSUE TITLE
Generate fancy markdown docs directly from the source-code files

### ISSUE THREAD

**Issue by ThomasLaPiana** [IABTechLab/fideslang#63]
### Is your feature request related to a specific problem?

We're adding as much documentation as we possible can to the pydantic models themselves for fideslang, and it's only going to get harder and more cumbersome to try to manage updating two separate places whenever we make a fideslang model change.

### Describe the solution you'd like

I'd like each of the data types to have a nice markdown table generated purely from the pydantic sauce and included as part of our docs

### Describe alternatives you've considered, if any

Using some kind of automated docs builder, it may exist

**Comment by sanders41** [comment]
FastAPI kind of does this with generating the open API docs. I wonder if there is some way for us to hook into that to also generate markdown.

**Comment by ThomasLaPiana** [comment]
yeah i used to include the raw JSON schemas as part of our docs, but it was just a bit too unwieldy...

I figure worst-case scenario we use a python script to generate some markdown for the docs. Wouldn't be too painful and I've seen other projects out there with much more elaborate docs build processes
