### ISSUE TITLE
Types are not being included with the package

### ISSUE THREAD

**Issue by sanders41** [IABTechLab/fideslang#99]
### Bug Description

When pip installing fideslang the types are not being included even though they are present so when using the package types have to be ignored.

#### Steps to Reproduce

1. Install fideslang
1. Run mypy

### Expected behavior

Types should be included.

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version: 1.3.3
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by ThomasLaPiana** [comment]
solved when I switched things over to `pyproject.toml`, as it includes package data by default
